### ISSUE TITLE
Dependency errors: NetworkX 2.8.8 and pyglet 2.0.9 require python 3.8

### ISSUE THREAD

**Issue by ellemcfarlane** [marmotlab/SCRIMP#2]
The repo requires python 3.7 but it seems NetworkX 2.8.8 and pyglet 2.0.9 (what got installed automatically as a dependency of gym I assume) both require python 3.8. I fixed the networkx issue by installing 2.6.3 but then when I run driver.py I run into the pyglet error which stems from gym's rendering module:

```
(myvenv) ~/SCRIMP
n-62-30-5(s222376) $ python3 driver.py
Traceback (most recent call last):
  File "driver.py", line 13, in <module>
    from mapf_gym import MAPFEnv
  File "SCRIMP/mapf_gym.py", line 11, in <module>
    from gym.envs.classic_control import rendering
  File "SCRIMP/myvenv/lib/python3.7/site-packages/gym/envs/classic_control/rendering.py", line 18, in <module>
    import pyglet
  File "SCRIMP/myvenv/lib/python3.7/site-packages/pyglet/__init__.py", line 19, in <module>
    raise Exception(f"pyglet {version} requires Python {MIN_PYTHON_VERSION_STR} or newer.")
Exception: pyglet 2.0.9 requires Python 3.8 or newer.
```
I tried pyglet 2.0.0 which docs say can use 3.7 but the 3.8 error still arose. I then tried pyglet 1.5.27 but then ran into another error on import:
```
    raise NoSuchDisplayException('Cannot connect to "%s"' % name)
pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"
```

Any suggestions? Should I just upgrade to python 3.8?

Running this on:
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Model name:            Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz
```

Also, I know it's a bit inconvenient, but maybe you all could make a docker image for people to download to avoid fighting all these dependency issues? Makes things much faster for those that want to run/modify your code :)

**Comment by wyt2019suzhou** [comment]
Thanks for your suggestion! This problem can be solved by using python3.8 directly

**Comment by ellemcfarlane** [comment]
Perfect! I got all dependencies to work although had to upgrade to tensorflow 2.2.0 and downgrade to protobuf 3.20.0 (had to for python 3.7 btw) due to this error:
```
(venv38) ~/SCRIMP
user $ python driver.py
Traceback (most recent call last):
  File "driver.py", line 5, in <module>
    import ray
  File "/zhome/ae/c/180898/SCRIMP/venv38/lib/python3.8/site-packages/ray/__init__.py", line 91, in <module>
    import ray._raylet  # noqa: E402
  File "python/ray/_raylet.pyx", line 103, in init ray._raylet
  File "/zhome/ae/c/180898/SCRIMP/venv38/lib/python3.8/site-packages/ray/exceptions.py", line 5, in <module>
    from ray.core.generated.common_pb2 import RayException, Language, PYTHON
  File "/zhome/ae/c/180898/SCRIMP/venv38/lib/python3.8/site-packages/ray/core/generated/common_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "/zhome/ae/c/180898/SCRIMP/venv38/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 796, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```
All this said: the original rendering issue was actually caused by me running this on a remote server without X11Forwarding. Once I enable X11F and use vglrun for OpenGL it will probably work.
